### ISSUE TITLE
Stats calculations going up but not coming back down again.

### ISSUE THREAD

**Issue by boars** [352Media/skilltree#3]
Two parts to this:
1. When you add a talent it adds to your stats, when you take away a talent it does not in turn remove the stats added. 
2. When you change your profile picture it adds the stats again based on what talents you have selected, so when you flick through them with multiple talents, the stats blow out rather quickly 

Otherwise, this is really rather delicious - have some cake. :cake:

**Comment by wimpyprogrammer** [comment]
Thanks so much for the bug report (and cake)!

I'm shocked that we haven't noticed or heard about this issue before since it's so obvious once you know what to look for.  I appreciate you taking the time to report it.  I believe #4 will merge soon and fix the issue.

**Comment by wimpyprogrammer** [comment]
My fix has merged so the stats should now calculate correctly.  I don't see the issue on dungeonsanddevelopers.com (which doesn't have my fix) so I think the problem was specific to the version on GitHub.  Thanks again for reporting the issues!
